### PR TITLE
create avtars and docs page

### PR DESCRIPTION
**Pull request by devsurajrai**
Suggestions are most welcomed. Please review.

### CODE REVIEW

**Comment by MuskanChhatrasal** [comment]
It looks Nice!!
Instead of creating separate getting started for particular component you can create a single getting started for including your complete component library.
Like in bootstrap by just including single link we can use any component in our project. 
Else it looks good.

**Review by Dev-AkshatGupta — APPROVED** [review]
LGTM you are ready to merge it :)

**Comment by ApurvaSawant11** [comment]
In addition to @MuskanChhatrasal's comment. The getting started link is for avatar.css. Is it a typo or are you using a separate link for each CSS component?

**Comment by devsurajrai** [comment]
> It looks Nice!! Instead of creating separate getting started for particular component you can create a single getting started for including your complete component library. Like in bootstrap by just including single link we can use any component in our project. Else it looks good.

Yeah I will implement that in the landing page where user can just copy a CDN and will be able to use all the components. This separate CDN is for those who would want to use only that particular component and not to mention it will also increase the performance.

**Comment by devsurajrai** [comment]
> LGTM you are ready to merge it :)

Thanks @Dev-AkshatGupta

**Comment by devsurajrai** [comment]
> In addition to @MuskanChhatrasal's comment. The getting started link is for avatar.css. Is it a typo or are you using a separate link for each CSS component?

not a typo. Its an idea.

**Pull request merged**
