### PR TITLE
create badge

### PR DESCRIPTION
**Pull request by devsurajrai**
Please review and provide your valuable feedback.

### CODE REVIEW

**Review by anik31 — APPROVED** [review]
LGTM

**Comment by devsurajrai** [comment]
> LGTM

Thanks for your review.

**Review by Dev-AkshatGupta — APPROVED** [review]
LGTM good UI Suraj keep on doing the good work :)

**Comment by devsurajrai** [comment]
> LGTM good UI Suraj keep on doing the good work :)

TYSM Merging

**Pull request merged**
